use Ejercicio16

Create table EMPLEADO (
COD_EMPLEADO varchar(9) CONSTRAINT PKEmpleado PRIMARY KEY,
NOMBRE varchar(30) not null,
APELLIDOS varchar(50) not null,
NIF char(9) not null UNIQUE,
DIRECCIÓN varchar(49),
TELÉFONO char(9),
SALARIO Money,
)

CREATE TABLE CAPACITADO(
COD_EMPLEADO varchar(9) CONSTRAINT FKCAPACITADO_EMPLEADO FOREIGN KEY REFERENCES EMPLEADO(COD_EMPLEADO),
CONSTRAINT PKCAPACITADO  PRIMARY KEY (COD_EMPLEADO)
)

CREATE TABLE NO_CAPACITADO(
COD_EMPLEADO varchar(9) CONSTRAINT FKNO_CAPACITADO_EMPLEADO FOREIGN KEY REFERENCES EMPLEADO(COD_EMPLEADO),
CONSTRAINT PKNO_CAPACITADO  PRIMARY KEY (COD_EMPLEADO)
)

CREATE TABLE CURSO(
COD_CURSO VARCHAR(9) CONSTRAINT PKCURSO  PRIMARY KEY,
NOMBRE varchar(30) not null,
DESCRIPCION varchar(40),
)

CREATE TABLE EDICION(
COD_CURSO varchar(9)
CONSTRAINT FKEDICION_CURSO FOREIGN KEY REFERENCES CURSO(COD_CURSO),
FECHA_CURSO date,
LUGAR varchar(20),
HORARIO time,
COD_CAPACIDAD varchar(9)NOT NULL 
CONSTRAINT FKEDICION_CAPACITADO FOREIGN KEY REFERENCES CAPACITADO(COD_EMPLEADO),
CONSTRAINT PKEDICION PRIMARY KEY (COD_CURSO, FECHA_CURSO)
)

CREATE TABLE RECIBE(
COD_EMPLEADO varchar(9)
CONSTRAINT FKRECIBE_EMPLEADO FOREIGN KEY REFERENCES EMPLEADO(COD_EMPLEADO),
COD_CURSO varchar(9),
FECHA_CURSO date,
CONSTRAINT FKRECIBE_EDICION FOREIGN KEY (COD_CURSO, FECHA_CURSO) REFERENCES EDICION(COD_CURSO, FECHA_CURSO),
CONSTRAINT PKRECIBE PRIMARY KEY (COD_EMPLEADO, FECHA_CURSO, COD_CURSO),
)
