
USE Ejercicio18

CREATE TABLE Area (
	CodArea INT CONSTRAINT PK_AREA PRIMARY KEY IDENTITY
)

CREATE TABLE Sede (
	CodSede INT CONSTRAINT PK_SEDE PRIMARY KEY IDENTITY
)

CREATE TABLE AreaSede (
	area INT,
	sede INT
	CONSTRAINT PK_AREASEDE PRIMARY KEY (area, sede)
	CONSTRAINT fk_area FOREIGN KEY (area) REFERENCES Area(CodArea),
	CONSTRAINT fk_sede FOREIGN KEY (sede) REFERENCES Sede(CodSede)
)

CREATE TABLE Profesor (
	DNI CHAR(9) CONSTRAINT PK_PORFE PRIMARY KEY,
	Encarga INT,
	Sede INT,
	CONSTRAINT FK_ENGARGA FOREIGN KEY (Encarga) REFERENCES Area(CodArea),
	CONSTRAINT FK_SEDEE FOREIGN KEY (Sede) REFERENCES Sede(CodSede),
)

CREATE TABLE Curso (
	CodCurso INT CONSTRAINT PK_CURSO PRIMARY KEY IDENTITY,
	Area INT,

	CONSTRAINT FK_AREAA FOREIGN KEY (Area) REFERENCES Area(CodArea),
)

CREATE TABLE Alumno (
	DNI CHAR(9) CONSTRAINT PK_ALUMNO PRIMARY KEY
)

CREATE TABLE Matricula (
	curso INT,
	alumno CHAR(9),

	CONSTRAINT PK_MATRICULA PRIMARY KEY (curso, alumno),
	CONSTRAINT FK_CURSO FOREIGN KEY (curso) REFERENCES Curso(CodCurso),
	CONSTRAINT FK_ALUM FOREIGN KEY (alumno) REFERENCES Alumno(DNI)
)

CREATE TABLE ProfesorCurso (
	profesor CHAR(9),
	curso INT,
	CONSTRAINT PK_PROFCURSO PRIMARY KEY (profesor, curso),
	CONSTRAINT FK_PROF FOREIGN KEY (profesor) REFERENCES Profesor(DNI),
	CONSTRAINT FK_CURSSS FOREIGN KEY (curso) REFERENCES Curso(CodCurso)
)

CREATE TABLE Coordenador (
	DNI CHAR(9) CONSTRAINT PK_COOR PRIMARY KEY
)
